#!/bin/sh

exec 2>&1

export SERVICE=ethminer-nvidia
export INSTANCENUM=`cat instancenum`
. /etc/libsh/loadsettings
. /etc/libsh/nvidia


if [ "$1" = "tty" ];then
	ETHMINER_BIND_TTY=""
fi
if [ "$ETHMINER_BIND_TTY" != "" ]; then
	#/usr/sbin/delservice.sh console${ETHMINER_BIND_TTY} > /dev/null
	sv stop console${ETHMINER_BIND_TTY}
	rm -f /var/service/console${ETHMINER_BIND_TTY}
	t=/dev/tty${ETHMINER_BIND_TTY}
	exec <$t >$t 2>&1 || exit 1
	#reset
	stty sane
fi

echo
echo "Starting with parameters:"
echo
set | grep "ETHMINER_"
echo

apiport=$((3433+$INSTANCENUM))
opts="-U --HWMON 2 --report-hashrate --exit --api-bind 127.0.0.1:${apiport}"

pool="${ETHMINER_POOL:-"eu1.ethermine.org:4444"}"
wallet="${ETHMINER_WALLET:-0x00747e59ee64851ecb100d18f3d51878463c0f94}"
worker="${ETHMINER_WORKER:-donate}"
scheme=${ETHMINER_SCHEME:-'stratum+tcp'}

if [ "${scheme}" = "http" ]; then
	opts="${opts} -P ${scheme}://${pool}/${wallet}/${worker}"
else
	opts="${opts} -P ${scheme}://${wallet}.${worker}@${pool}"
fi
opts="${opts} ${ETHMINER_TAIL_OPTS}"

echo "Start ethminer with opts \"$opts\" after 3 sec"
sleep 3

nvidia_load_drv

#nvidia opencl only for hwmon
export LD_LIBRARY_PATH=/opt/nvidia/lib

exec /root/ethminer ${opts}

